### ISSUE TITLE
Crash when clicking on menu items in left pane

### ISSUE THREAD

**Issue by escarlson** [pop-os/gnome-control-center#118]
I just updated from 20.04 to 20.10, and gnome-control-center now crashes when clicking on any of the settings on the left. Additionally, no content is shown on the right pane of the window. Here is the backtrace from gdb:
```
Starting program: /usr/bin/gnome-control-center 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after vfork from child process 7050]
[New Thread 0x7fffe98ca640 (LWP 7052)]
[New Thread 0x7fffe90c9640 (LWP 7053)]
[New Thread 0x7fffe88c8640 (LWP 7054)]
[New Thread 0x7fffdbc41640 (LWP 7055)]
[New Thread 0x7fffd99bc640 (LWP 7056)]
[New Thread 0x7fffd91bb640 (LWP 7057)]
[New Thread 0x7fffd89ba640 (LWP 7058)]
[New Thread 0x7fffcf5f1640 (LWP 7059)]

(gnome-control-center:7046): Gtk-CRITICAL **: 15:03:32.578: Error building template class 'CcBackgroundPanel' for an instance of type 'CcBackgroundPanel': .:2:747 Invalid property: HdyClamp.maximum_width

(gnome-control-center:7046): background-cc-panel-CRITICAL **: 15:03:32.619: cc_background_preview_set_item: assertion 'CC_IS_BACKGROUND_PREVIEW (self)' failed

(gnome-control-center:7046): Gtk-CRITICAL **: 15:03:32.619: gtk_container_add: assertion 'GTK_IS_WIDGET (widget)' failed

(gnome-control-center:7046): GLib-GObject-CRITICAL **: 15:03:32.619: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(gnome-control-center:7046): Gtk-CRITICAL **: 15:03:32.619: gtk_size_group_add_widget: assertion 'GTK_IS_WIDGET (widget)' failed

(gnome-control-center:7046): Gtk-CRITICAL **: 15:03:32.620: gtk_container_add: assertion 'GTK_IS_CONTAINER (container)' failed

(gnome-control-center:7046): Gtk-CRITICAL **: 15:03:32.620: gtk_widget_show_all: assertion 'GTK_IS_WIDGET (widget)' failed

(gnome-control-center:7046): GLib-GObject-WARNING **: 15:03:32.620: invalid (NULL) pointer instance

(gnome-control-center:7046): GLib-GObject-CRITICAL **: 15:03:32.620: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(gnome-control-center:7046): Gtk-CRITICAL **: 15:03:34.731: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed
**
cc-window:ERROR:../shell/cc-window.c:121:remove_all_custom_widgets: assertion failed: (parent == GTK_WIDGET (self->top_right_box) || parent == GTK_WIDGET (self->top_left_box))
Bail out! cc-window:ERROR:../shell/cc-window.c:121:remove_all_custom_widgets: assertion failed: (parent == GTK_WIDGET (self->top_right_box) || parent == GTK_WIDGET (self->top_left_box))

Thread 1 "gnome-control-c" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt full
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
        set = 
            {__val = {0, 93825011414128, 186, 186, 140737315969216, 140737314557002, 0, 140737488340784, 140737315965952, 4122580672, 93825011414128, 186, 140737315972288, 4, 140737315965856, 129}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x00007ffff59db864 in __GI_abort () at abort.c:79
        save_stage = 1
        act = 
          {__sigaction_handler = {sa_handler = 0x555555a71c00, sa_sigaction = 0x555555a71c00}, sa_mask = {__val = {140737350630327, 93823560581168, 140737488341136, 4294953072, 93824997596160, 0, 140733193388033, 140737350877803, 93826899247104, 93824997596160, 0, 0, 6604110277215704576, 93824993761584, 140737351376352, 93824997596160}}, sa_flags = 176, sa_restorer = 0x5555556c951b}
        sigs = 
            {__val = {32, 140737314591227, 2048, 140737315965856, 93824993760539, 39, 93825000907840, 140737350599556, 199, 6604110277215704576, 93825011366832, 199, 93825011366832, 199, 175, 1}}
#2  0x00007ffff7c4bb1c in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff7caa3ff in g_assertion_message_expr ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00005555555bca3b in  ()
--Type <RET> for more, q to quit, c to continue without paging--c
#5  0x00007ffff7d769cd in g_cclosure_marshal_VOID__STRINGv () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff7d73b56 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff7d8cb9f in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff7d8cd83 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00005555555bb07e in  ()
#10 0x00007ffff7d76fc1 in g_cclosure_marshal_VOID__OBJECTv () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff7d73b56 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff7d8cb9f in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff7d8cd83 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff7641cae in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007ffff77f6cff in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00007ffff7d73b56 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff7d8cb9f in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff7d8cd83 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff75fdfcc in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007ffff7d76d14 in g_cclosure_marshal_VOID__BOXEDv () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007ffff7d73b56 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007ffff7d8cb9f in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff7d8cd83 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff75fafc7 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#25 0x00007ffff75fc6bb in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#26 0x00007ffff75ff803 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#27 0x00007ffff75c50c0 in gtk_event_controller_handle_event () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#28 0x00007ffff779741d in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#29 0x00007ffff77f07ec in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#30 0x00007ffff7d73b56 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#31 0x00007ffff7d8bee9 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#32 0x00007ffff7d8cd83 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#33 0x00007ffff7799514 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#34 0x00007ffff7647d50 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#35 0x00007ffff7649a93 in gtk_main_do_event () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#36 0x00007ffff7321e89 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#37 0x00007ffff73568e6 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#38 0x00007ffff7c814eb in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007ffff7c81798 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#40 0x00007ffff7c81863 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#41 0x00007ffff7ea054d in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#42 0x00005555555b6ed8 in main ()
(gdb) 


```
lsb_release -a:
```
LSB Version:	core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Pop
Description:	Pop!_OS 20.10
Release:	20.10
Codename:	groovy
```
Screenshot: ![Screenshot from 2020-09-27 14-54-42](https://user-images.githubusercontent.com/10640906/94375731-fd6f6400-00d2-11eb-91bb-bb32f584fb5b.png)

Please let me know if any other information might be helpful.

**Comment by escarlson** [comment]
Looks like this is working after gnome-control-center was updated yesterday. From the apt log:
`Upgrade: gnome-control-center:amd64 (1:3.38.0-1ubuntu1pop0~1600182470~20.10~345ee4e, 1:3.38.0-1ubuntu1pop1~1600878607~20.10~d3d56ba)`
